### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by andreash92** [gettyimages/hubot-dashboard#1]
seems very interesting, but how to get start using it??

**Comment by mapitman** [comment]
@CaseyMacPherson ??

**Comment by mapitman** [comment]
The developer who was maintaining this project left the company. He has a [fork](https://github.com/CaseyMacPherson/hubot-dashboard) with more commits. I'll probably delete our fork since he has all the knowledge on the project. Open a new issue on his fork.
